# Generated by Django 4.1.7 on 2023-02-22 11:34

from django.db import migrations, models
import django.db.models.deletion
import main.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст заявки')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Телеграм user_id')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('contractor', 'Подрядчик'), ('admin', 'Заказчик проекта'), ('manager', 'Менеджер')], max_length=10, verbose_name='Тип пользователя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название тарифа')),
                ('limit_orders', models.IntegerField(verbose_name='Лимит заявок в месяц')),
                ('limit_time_answer', models.IntegerField(verbose_name='Время ответа на заявку в часах')),
                ('can_see_contractor', models.BooleanField(default=False, verbose_name='Возможность видеть контакты подрядчика')),
                ('can_attach_contractor', models.BooleanField(default=False, verbose_name='Закрепить за собой подрядчика')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст заявки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Заказ создан')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, verbose_name='Заказ выполнен')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Заказ оплачен')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Заказ закрыт')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='main.person', verbose_name='клиент')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_orders', to='main.person', verbose_name='подрядчик')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField(blank=True, verbose_name='Стоимость заказа')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person', verbose_name='договор подрядчика')),
            ],
            options={
                'verbose_name': 'договор подрядчика',
                'verbose_name_plural': 'договора подрядчиков',
            },
        ),
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_limit_to', models.DateTimeField(default=main.models.end_period, verbose_name='конец периода')),
                ('orders_left', models.IntegerField(verbose_name='остаток заявок')),
                ('is_working', models.BooleanField(default=True, verbose_name='действующий')),
                ('attach_contactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_contracts', to='main.person', verbose_name='закрепленный подрядчик')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to='main.person', verbose_name='договор')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tariff', verbose_name='тариф')),
            ],
            options={
                'verbose_name': 'договор клиента',
                'verbose_name_plural': 'договора клиентов',
            },
        ),
    ]
