# Generated by Django 4.1.7 on 2023-02-22 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Старт подписки')),
            ],
            options={
                'verbose_name': 'договор клиента',
                'verbose_name_plural': 'договора клиентов',
            },
        ),
        migrations.CreateModel(
            name='ExampleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст заявки')),
            ],
            options={
                'verbose_name': 'пример заявки',
                'verbose_name_plural': 'примеры заявок',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Заказ создан')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, verbose_name='Заказ выполнен')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('telegram_id', models.SmallIntegerField(verbose_name='Телеграм ID')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('contractor', 'Подрядчик'), ('admin', 'Заказчик проекта'), ('manager', 'Менеджер')], max_length=10, verbose_name='Тип пользователя')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название тарифа')),
                ('orders_limit', models.IntegerField(verbose_name='Лимит заявок в месяц')),
                ('validity', models.DurationField(default=datetime.timedelta(days=30), verbose_name='Срок действия')),
                ('answer_delay', models.DurationField(verbose_name='Время ответа на заявку')),
                ('contractor_contacts_availability', models.BooleanField(default=False, verbose_name='Возможность видеть контакты подрядчика')),
                ('personal_contractor_available', models.BooleanField(default=False, verbose_name='Закрепить за собой подрядчика')),
            ],
            options={
                'verbose_name': 'тариф',
                'verbose_name_plural': 'тарифы',
            },
        ),
        migrations.CreateModel(
            name='OrderComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='main.person', verbose_name='Author')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='main.order', verbose_name='Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_orders', to='main.person', verbose_name='подрядчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='main.clientsubscription', verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_subscriptions', to='main.person', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_subscriptions', to='main.person', verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='main.tariff', verbose_name='Тариф'),
        ),
    ]
