# Generated by Django 4.1.7 on 2023-02-25 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'контакты пользователя', 'verbose_name_plural': 'контакты пользователей'},
        ),
        migrations.AlterField(
            model_name='client',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='main.person', unique=True, verbose_name='Заказчик'),
        ),
    ]
