# Generated by Django 4.1.7 on 2023-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=500, verbose_name='Стоимость работ'),
        ),
    ]
