# Generated by Django 4.1.7 on 2023-02-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ordercomments_order_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Order',
            new_name='order',
        ),
    ]
