# Generated by Django 4.1.7 on 2023-02-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230222_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampleorder',
            options={'verbose_name': 'пример заявки', 'verbose_name_plural': 'примеры заявок'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'тариф', 'verbose_name_plural': 'тарифы'},
        ),
    ]
