# Generated by Django 4.1.7 on 2023-02-25 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clientsubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='salary',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость работ'),
        ),
    ]
