# Generated by Django 4.1.7 on 2023-02-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_complaint_admin_alter_complaint_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Жалоба закрыта'),
        ),
    ]
