# Generated by Django 4.1.7 on 2023-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='active',
            field=models.BooleanField(default=False, verbose_name='исполнитель утвержден'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='comment',
            field=models.TextField(blank=True, verbose_name='заявка на утверждение'),
        ),
    ]
