# Generated by Django 4.1.7 on 2023-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_complaint_closed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'жалоба', 'verbose_name_plural': 'жалобы'},
        ),
        migrations.AddField(
            model_name='manager',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='owner',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
