# Generated by Django 4.1.7 on 2025-03-05 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_complaint_options_manager_active_owner_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                ("description", models.TextField(verbose_name="Описание услуги")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость услуги",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Скидка %",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="main.contractor",
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "услуга",
                "verbose_name_plural": "услуги",
            },
        ),
        migrations.CreateModel(
            name="ServiceSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Оплачен"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_sets",
                        to="main.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="sets", to="main.service", verbose_name="Услуги"
                    ),
                ),
            ],
            options={
                "verbose_name": "сет услуг",
                "verbose_name_plural": "сеты услуг",
            },
        ),
        migrations.CreateModel(
            name="ContractorSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало подписки"
                    ),
                ),
                (
                    "next_payment_at",
                    models.DateTimeField(verbose_name="Следующий платеж"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активна"),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID платежа"
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contractor_subscriptions",
                        to="main.contractor",
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "подписка исполнителя",
                "verbose_name_plural": "подписки исполнителей",
            },
        ),
    ]
