# Generated by Django 4.1.7 on 2023-02-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contractor_active_contractor_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='declined',
            field=models.BooleanField(default=False, verbose_name='Заявка отклонена'),
        ),
    ]
