# Generated by Django 4.1.7 on 2025-03-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_service_serviceset_contractorsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "категория услуг",
                "verbose_name_plural": "категории услуг",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="service_photos/",
                verbose_name="Фото услуги",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="main.servicecategory",
                verbose_name="Категория",
            ),
        ),
    ]
